PlaceOS/rest-api

- src/controllers/systems.cr
- src/session.cr
also updates session to use the tagged logger
> feat: add support for triggers

- Dockerfile
- shard.lock
- spec/drivers_spec.cr
- spec/helper.cr
- spec/modules_spec.cr
- spec/system-triggers_spec.cr
- spec/systems_spec.cr
- src/constants.cr
- src/controllers/application.cr
- src/controllers/authentications.cr
- src/controllers/domains.cr
- src/controllers/drivers.cr
- src/controllers/modules.cr
- src/controllers/oauth_applications.cr
- src/controllers/repositories.cr
- src/controllers/root.cr
- src/controllers/system-triggers.cr
- src/controllers/systems.cr
- src/controllers/triggers.cr
- src/controllers/users.cr
- src/controllers/zones.cr
- src/error.cr
- src/utilities/current-user.cr
uses headers to indicate the data being returned
provides a link to the next set of results (to simplify infinite scrolling)
> feat: improve listing and pagination of data

- src/controllers/application.cr
> fix(controller:application): check `Content-Type` starts with media-type 'application/json'

- shard.lock
- spec/modules_spec.cr
- spec/systems_spec.cr
- src/controllers/modules.cr
- src/controllers/settings.cr
- src/controllers/systems.cr
Resolves PlaceOS/backoffice/issues/8
> feat(controller:settings|modules): implement `GET ../:id/settings`

- shard.lock
- src/controllers/zones.cr
Also fixes an issue where support users can't get individual zones
> feat(zones): add filtering zones by parent

- shard.lock
- src/controllers/zone_metadata.cr
designed to these specs: https://placeos.docs.apiary.io/#reference/0/zones/get-zone-metadata
> feat(zone_metadata): initial work metadata API

- Dockerfile
- src/controllers/cluster.cr
otherwise we wouldn't need to jump through all those hoops getting `ping` working and could have done it with raw packets.
> feat(dockerfile): don't run process as root

- shard.lock
- spec/session_spec.cr
- src/controllers/drivers.cr
- src/controllers/modules.cr
- src/controllers/webhook.cr
> feat(controllers): add `../drivers/:id/compiled` and `../modules/:id/load`

- shard.lock
- shard.yml
- src/rest-api/controllers/settings.cr
Resolves comment by @MrYuion in PlaceOS/backoffice#47
> fix(controller:settings): decrypt response for creates and updates

- src/placeos-rest-api/controllers/systems.cr
> feat(systems): helper for finding by resource email

- shard.lock
- shard.yml
- spec/triggers_spec.cr
- src/placeos-rest-api/controllers/triggers.cr
- add `GET ../triggers/:id/instances -> Array(TriggerInstance)`
- add `instances` param to `GET ../triggers/:id` to include instances.
Resolves #27
> feat(controller:triggers): add instances route

- shard.lock
- shard.yml
- spec/modules_spec.cr
- spec/systems_spec.cr
- spec/triggers_spec.cr
- src/placeos-rest-api/controllers/systems.cr
- Update `neuroplastic` (Resolves #4)
- Add `emails` param to `Systems` (Resolves #29)
> fix: Module search

- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/repositories.cr
> fix(controller:drivers): synchronous recompile

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/root.cr
Uses `RUBBER_SOUL_URI` which defaults to `http://rubber-soul:3000`
> refactor(root): use RubberSoul::Client

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/system-triggers.cr
- Add a `complete` param for `show` and `index`
* includes `ControlSystem`'s `name` and `id` field
* merges `Trigger` name
* defaults to `true`
- Check for existence of parent `ControlSystem` before...
* `show`
* `update`
* `destroy`
> feat(controller:system-triggers): `complete` param for show & index, check for system

- src/placeos-rest-api/controllers/users.cr
allowing users to access SSO resources
> feat(users): support for managing SSO resource tokens

- shard.lock
- shard.yml
- spec/helper.cr
- spec/modules_spec.cr
- spec/session_spec.cr
- spec/settings_spec.cr
- spec/system-triggers_spec.cr
- spec/systems_spec.cr
- spec/users_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
Also sort by index by `name` as a keyword
> refactor: update placeos-models

- shard.lock
- shard.yml
- spec/helper.cr
- spec/metadata_spec.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/utilities/responders.cr
Nested objects were being merged rather than replaced on save. 
Fixes #49
> fix(controller:metadata): consistent updates to `details`

- shard.lock
- shard.yml
- spec/modules_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/systems.cr
- Refactor to use lazy getters
- Refactor `Application#set_request_id`
> refactor: lazy getters

- .gitignore
- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/systems.cr
- Set `search_field` for `Drivers` & `Systems` controllers
- Update `neuroplastic` to `v1.7.0`
> improvement: update query generation

- shard.lock
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/utilities/responders.cr
and zone metadata, guests must supply a name param
> feat: allow guest access to zone details

- shard.lock
- spec/drivers_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/session.cr
- src/placeos-rest-api/utilities/responders.cr
- Correct some typos
- Fix a failing drivers spec
- Convert a `when` to a `case ... in`
> fix: failing drivers index

- spec/modules_spec.cr
fix a flakey test regarding updating the connection status of a logic module
> test: modules connected update

- spec/brokers_spec.cr
- spec/drivers_spec.cr
- spec/helper.cr
- spec/modules_spec.cr
- spec/repositories_spec.cr
- spec/systems_spec.cr
- spec/triggers_spec.cr
- spec/zones_spec.cr
- src/placeos-rest-api/controllers/authentications.cr
- src/placeos-rest-api/controllers/brokers.cr
- src/placeos-rest-api/controllers/cluster.cr
- src/placeos-rest-api/controllers/domains.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/oauth_applications.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/utilities/current-user.cr
- Adds lazy getters to controllers
- More unique names for testing updates
- Fix a boolean parameter bug in modules controller
> refactor: add lazy getters

- shard.lock
- shard.yml
- spec/helper.cr
- spec/root_spec.cr
- src/placeos-rest-api/controllers/root.cr
- Add validation to `/signal`
- Add specs for `/signal`
> test(controller:root): spec signal api

- src/placeos-rest-api/session.cr
> feat(session): provide some more error context to logs

- .gitignore
- .travis.yml
- Dockerfile.test
- README.md
- docker-compose.yml
- entrypoint.sh
- test
> fix: docker compose test

- src/placeos-rest-api/controllers/modules.cr
> style(controllers): use a consistent slash prefix for routes

- docker-compose.yml
- spec/systems_spec.cr
Adds spec created whilst diagnosing a regression. 
Additionally DRYs out some specs
> [SPEC] systems adding and removal of a module

- shard.lock
- shard.yml
- spec/drivers_spec.cr
- spec/helper.cr
- spec/modules_spec.cr
- spec/settings_spec.cr
- spec/system-triggers_spec.cr
- spec/systems_spec.cr
Locally, the spec run time dropped for 30 seconds to 13 seconds.
> spec: remove sleeps

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/modules.cr
Note, looks like this fix was needed due to bug in action-controller
Related to PlaceOS/backoffice/issues/154
> fix(controller:drivers): use HTTP status type directly

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/users.cr
Fix a privilege escalation vector via bulk assignment on the user update route.
> fix(controllers:user): prevent privilege escalation via bulk assignment

- shard.yml
- spec/users_spec.cr
- src/placeos-rest-api/controllers/users.cr
Fixes an exception raised by attempting to read from a drained IO
> fix(controller:users): pull String out of IO for double parse

- .github/workflows/test.yml
- Dockerfile
- Dockerfile.test
- shard.lock
- shard.override.yml
- shard.yml
- src/config.cr
- Update to build to crystal v0.36.0
- Add `PLACE_VERBOSE_CLUSTERING` to emit verbose clustering logs
> chore: crystal v0.36.0

- Dockerfile
- Dockerfile.test
- shard.lock
- spec/helper.cr
> chore: crystal 0.36.1

- shard.lock
- shard.override.yml
- src/placeos-rest-api/controllers/repositories.cr
Correction to interface repository pull logic.
> fix(controller:repositories): force compile interface repositories

- shard.lock
- spec/users_spec.cr
- src/placeos-rest-api/controllers/users.cr
@caspiano out of interest is the email lookup case-insensitive?
If not we should probably downcase email addresses in the model before they are saved
> feat(users): find user using email or id

- shard.lock
- shard.override.yml
- shard.yml
- spec/helper.cr
- src/config.cr
- src/placeos-rest-api.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/utilities/current-user.cr
also fix warnings generated on crystal 0.36.1
> feat: add logstash support

- src/placeos-rest-api/controllers/authentications.cr
Restrict authentication routes to admin
> fix: auth admin

- shard.lock
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/systems.cr
Minor DRY out of a method that accesses module state.
> refactor(controllers): DRY out access to module state

- shard.lock
- shard.override.yml
- shard.yml
- spec/helper.cr
- src/app.cr
- src/config.cr
- src/logging.cr
- src/placeos-rest-api.cr
- src/placeos-rest-api/session.cr
Update to place-labs/log-backend that fixes a cycle in the backend. 
Also as a consequence of reordering log configuration, all logs are in the same style now (including startup/shutdown).
> fix: logging

- shard.lock
- shard.yml
- spec/helper.cr
- src/placeos-rest-api/controllers/root.cr
Add a healthcheck that ensures the presence of etcd/rethinkdb/redis
Closes #113
> Improve healthcheck to ensure ability to connect to critical resources

- shard.lock
Bumps etcd and hound-dog libraries.
> chore(shard.lock): bump etcd

- src/placeos-rest-api/controllers/users.cr
> fix(users controller): allow assignment of admin attributes

- shard.lock
- shard.yml
> chore: bump placeos-models

- .github/workflows/test.yml
- shard.lock
- shard.yml
- src/logging.cr
Register the log level change signal handler.
Closes #124
> feat(logging): register log level change signals

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/repositories.cr
Add support for listing driver branches
Closes #132
> feat(controllers/repositories): listing driver branches

- shard.lock
- shard.override.yml
- shard.yml
- src/logging.cr
> fix(logging): set progname

- .github/workflows/ci.yml
- .github/workflows/test.yml
- Dockerfile.test
- docker-compose.yml
- entrypoint.sh
- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/users.cr
- test
Render errors in the destroy route of `users`
Waiting on PlaceOS/models#89
> feat(controllers/user:destroy): render errors

- Dockerfile
- shard.lock
- spec/root_spec.cr
- src/placeos-rest-api/controllers/root.cr
- src/placeos-rest-api/controllers/schema.cr
- src/placeos-rest-api/controllers/systems.cr
also fix warning related to metadata
> feat: add JSON schema CRUD routes

- shard.lock
- shard.yml
- spec/metadata_spec.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/utilities/responders.cr
- Fix how some results are rendered in the `Users` controller. 
- Fix an information leak on the `groups` endpoint
> performance: improve how users are rendered

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/systems.cr
- test
A simple change, using a PR on its way (hopefully) into crystal.
> perf(controller/systems): use tally_by

- src/placeos-rest-api/controllers/repositories.cr
Trigger a pull in case of a repository pull failure
> fix(api/repositories): pull on each pull request

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/repositories.cr
Fixes an issue that was breaking CI against nightly
> chore: update rethinkdb-orm

- shard.lock
Bump to get changes to client.
> chore: bump placeos-core

- .github/workflows/ci.yml
- Dockerfile
- shard.lock
- shard.override.yml
- shard.yml
- spec/api_key_spec.cr
- spec/helper.cr
- src/placeos-rest-api/controllers/api_keys.cr
- src/placeos-rest-api/utilities/current-user.cr
- src/placeos-rest-api/utilities/responders.cr
> feat: add api key CRUD methods

- src/placeos-rest-api/controllers/api_keys.cr
we'll use this to help authenticate staff-api using X-API-Keys
if X-API-key header is set, it'll use this route to obtain the JWT data
> feat(api-keys): provide a method for inspecting the keys JWT

- shard.lock
- spec/helper.cr
Lock user creation to prevent the creation of redundant users in specs
> test: lock mock user creation

- .github/workflows/ci.yml
- .hadolint.yaml
- Dockerfile
- Dockerfile.test
Add a hadolint step to the CI pipeline
> ci: add hadolint

- shard.lock
- shard.yml
- spec/root_spec.cr
- src/placeos-rest-api/controllers/cluster.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/root.cr
- src/placeos-rest-api/controllers/systems.cr
Updates to ensure branch of repository accounted for when fetching commits
Related https://github.com/PlaceOS/compiler/issues/41
> fix(api:repositories): account for branches in commit listing

- src/placeos-rest-api/controllers/cluster.cr
Catch promise failures and log them when requesting status from core nodes
> fix(api:cluster): improve error handling when requesting core status

- spec/modules_spec.cr
- src/placeos-rest-api/controllers/modules.cr
> fix(api/modules): remove parent index query

- src/placeos-rest-api/utilities/responders.cr
> fix(responders): callback skipped on model creation

- src/config.cr
- src/placeos-rest-api/utilities/current-user.cr
as javascript doesn't support setting headers on websocket connections
> feat(utilities current user): x-api-key needs param support

- spec/root_spec.cr
- src/placeos-rest-api/controllers/root.cr
Dispatch endpoint updated in PlaceOS/dispatch/pull/10
> refactor: use new dispatch endpoint

- .github/workflows/ci.yml
- test
Kick-off migration to use centralised workflows
> ci: test github's reusable flow

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/root.cr
Update some symbols as part of the `search-ingest` name change
> refactor: `rubber-soul` -> `search-ingest`

- docker-compose.yml
- shard.lock
- shard.yml
- spec/http_mocks.cr
- spec/websocket/session_spec.cr
- test
Updates `etcd-crystal` to support etcd > 3.3
> build: update `crystal-etcd`

- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/websocket/session.cr
Component of https://github.com/PlaceOS/core/issues/126
> feat(api): forward `user_id` for module executes

- src/placeos-rest-api/controllers/mqtt.cr
we are changing which bit we check to signal deny
> fix(mqtt controller): deny flag is also a read flag

- shard.lock
- spec/controllers/brokers_spec.cr
- spec/controllers/drivers_spec.cr
- spec/controllers/modules_spec.cr
- spec/controllers/mqtt_spec.cr
- spec/controllers/settings_spec.cr
- spec/controllers/systems_spec.cr
- spec/websocket/session_spec.cr
- src/placeos-rest-api/controllers/modules.cr
Runs all pending spec except for those that need core
> test: run pending spec

- spec/controllers/settings_spec.cr
Tightens a spec so an expectation failure is raised rather than an exception.
> test(settings): stricter spec to avoid exception

- src/placeos-rest-api/controllers/root.cr
> feat(root): add additional logging to signal requests

- .github/workflows/ci.yml
- src/placeos-rest-api/controllers/root.cr
Expose platform metadata endpoint
> fix(root): expose `/platform`

- src/constants.cr
- src/placeos-rest-api/controllers/flux.cr
with an aim to maintain compatibility with influx clients
> feat: add a flux query route

- src/placeos-rest-api/controllers/systems.cr
we forgot to apply the updated response object from core client with the driver status code
this fixes the response to return valid JSON
> fix(systems execute): fix response using driver status codes

- shard.lock
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/zones.cr
Updates to the driver exec silently broke a few interfaces.
**Benefits**
Interface will be less broken 🤷
> fix(controllers/modules): extract status from exec response

- .github/workflows/ci.yml
attempt to fix CI for todo generation
> ci: set original commit for TODO purposes

- shard.lock
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/settings.cr
Sets modifier in `settings` and `metadata` routes
> feat: set modifier for metadata and settings

- spec/controllers/modules_spec.cr
- spec/controllers/systems_spec.cr
- spec/controllers/users_spec.cr
- src/placeos-rest-api/controllers/users.cr
A param with a single email on the index route will now return that user if present within current authority 
**Benefits**
Mimics older version of PlaceOS so same processes can be used
**Applicable issues**
Closes #257
> feat(user): add email param on index

- shard.lock
- src/placeos-rest-api/utilities/responders.cr
- src/placeos-rest-api/websocket/session.cr
- src/placeos-rest-api/websocket/session/response.cr
so frontends can process results as required
> feat: add driver response codes to public API

- shard.lock
- shard.override.yml
- shard.yml
- src/placeos-rest-api/controllers/metadata.cr
Adds an index method to `Metadata`
**Benefits**
Simple queries of metadata are now possible.
See https://github.com/PlaceOS/models/pull/164 for details
**Applicable issues**
- Fixes #250
> feat(controller/metadata): add an index method

- src/placeos-rest-api/controllers/users.cr
where external systems are storing user-ids they should continue to function as expected
> feat(controllers/users): ensure user_id continuity

- shard.lock
- src/placeos-rest-api/controllers/metadata.cr
Adds a deep merge to the `PATCH` verb of the `Metadata` controller
> feat(metadata): PATCH to patch `details`, PUT to replace

- src/placeos-rest-api/controllers/users.cr
previously this had to be configured in authority.internals - the old method is still useful where there are multiple auth sources with different behaviours or scopes
> feat(users): resource token to default to first oauth app

- shard.lock
- src/placeos-rest-api/controllers/repositories.cr
> feat(repositories): new method for repository pull feedback

- shard.lock
- src/placeos-rest-api/controllers/users.cr
also adds a flag for forcing a hard delete of a user
> feat(users): add route for reviving a deleted user

- shard.lock
> chore(shard.lock): bump neuroplastic

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/users.cr
adds an `include_metadata` flag
> feat(users): optionally include user metadata

- shard.lock
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/users.cr
adds ref param which allows pagination without using offset, which should prevent duplicate values in results
> feat(application): improve query result accuracy

- shard.lock
- src/placeos-rest-api/controllers/users.cr
limits them to the other users on the current domain and public information they could obtain via the show method
> feat(users): allow any authenticated user to list users

- src/placeos-rest-api/utilities/scopes.cr
> fix(utilities/scopes): add `public` scope to scope list API

- src/placeos-rest-api/utilities/current-user.cr
> feat(utilities/current-user): log when an API key is being used

- spec/controllers/systems_spec.cr
- src/placeos-rest-api/controllers/systems.cr
use lowercase emails for querying via the dedicated route
allow using email as an ID
> feat(systems): additional options for querying using email

- OPENAPI_DOC.yml
- docker-compose.yml
- shard.lock
- shard.override.yml
- src/placeos-rest-api/controllers/repositories.cr
for querying details before a repo is added, such as default branch, branches and available commits
> feat(repositories): add additional helper methods

- shard.lock
- src/placeos-rest-api/controllers/cluster.cr
core-client was implementing a future protocol
> fix(shard.lock): bump core-client to fix cluster listing

- shard.lock
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/websocket/session.cr
ensures requests from backoffice / websocket are routed to the correct driver
driver-driver comms are already correct
> fix: edge exec lookup

- OPENAPI_DOC.yml
- shard.lock
- src/placeos-rest-api/controllers/repositories.cr
> feat(repositories): add branch support

- OPENAPI_DOC.yml
- src/placeos-rest-api/controllers/webrtc.cr
also remove metadata from metadata from results
> fix(webrtc): make index route public

- shard.lock
- spec/controllers/notifications_spec.cr
- src/placeos-rest-api/controllers/notifications.cr
- src/placeos-rest-api/controllers/notifications/google.cr
- src/placeos-rest-api/controllers/notifications/microsoft.cr
improves performance and reduces needless JSON parsing
> feat(notifications): publish on subscription id

- GPT.yml
- OPENAPI_DOC.yml
- src/placeos-rest-api/controllers/chat_gpt.cr
- src/placeos-rest-api/controllers/chat_gpt/plugins.cr
API endpoints for GPT plugins on Copilot and OpenAI
> feat(chat_gpt/plugin): interaction API

- src/placeos-rest-api/controllers/repositories.cr
for integration testing before release
> feat: build service staging

- src/placeos-rest-api/controllers/repositories.cr
when the default branch is not specified
> fix(repositories): list the files on the correct branch [PPT-1397]
