- shard.lock
- src/controllers/drivers.cr
- src/controllers/modules.cr
- src/controllers/repositories.cr
- src/controllers/settings.cr
- src/controllers/system-triggers.cr
- src/controllers/systems.cr
- src/controllers/triggers.cr
- src/controllers/users.cr
- src/controllers/zones.cr
Needs a spec, we'll need this for backoffice
@MrYuion in the latest version of Engine the driver repositories can be added to the database. So we need to be able to administer the driver git repos that are available in backoffice:
This is the data model / fields in the table
https://github.com/aca-labs/crystal-engine-models/blob/master/src/engine-models/repository.cr
> Repositories api

- shard.lock
- shard.yml
- src/rest-api/controllers/repositories.cr
- Make the `driver` param for `GET ../repositories/:id/commits` optional
- Add `GET ../repositories/interfaces` to show loaded interfaces
> feat(controller:repositories): handle `Interface` type repositories

- src/rest-api/controllers/systems.cr
- src/rest-api/session.cr
no need to re-create the object multiple times
> feat: use the shared discovery instance

- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/brokers.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/zones.cr
DRY out setting of headers when returning a fixed-length query
> refactor(controllers): set_collection_headers shortcut for fixed collections

- src/placeos-rest-api/controllers/users.cr
as we might want a user on a domain that doesn't have backoffice for auto-authing a UI for instance
> feat: allow users to be created for other domains

- shard.lock
- shard.yml
- spec/helper.cr
- spec/zone_metadata_spec.cr
- src/placeos-rest-api/controllers/zone_metadata.cr
Correctly filter metadata by name.
Previously it would the parent's metadata for the children query.
Also added a few tests.
> Fix: correctly filter zone metadata

- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/repositories.cr
Adds a new route `GET ../repositories/:id/branches` that returns an `Array(String)` if  the `Repository` is of type `Interface`
> feat(controller:repositories): support branch listing for interface repositories

- .travis.yml
- shard.yml
- src/placeos-rest-api/controllers/systems.cr
`ControlSystem`'s `before_save` callbacks were missed previously.
> fix(controller:systems): run save callbacks on remove module

- shard.yml
- src/placeos-rest-api/controllers/metadata.cr
Include the parent Zone's metadata via the default `true` param `include_parent`
fixes #47
> fix(controller:metadata): default include parent metadata in children route

- src/placeos-rest-api/controllers/users.cr
the use case is for assigning roles and attributes after login, most likely by a background service
> feat(users): provide a method for updating admin attributes 

- shard.yml
- src/placeos-rest-api/controllers/repositories.cr
A small change to the `Repositories` controller.
Previously limiting the number of commits was done via a `count` param, now the param 
`limit` is used.
> refactor: use `limit` rather than `count` for commit listing

- docker-compose.yml
- shard.lock
- shard.yml
- spec/edges_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/authentications.cr
- src/placeos-rest-api/controllers/brokers.cr
- src/placeos-rest-api/controllers/cluster.cr
- src/placeos-rest-api/controllers/domains.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/edge.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/oauth_applications.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/error.cr
- src/placeos-rest-api/session.cr
- src/placeos-rest-api/utilities/core_discovery.cr
Implements the edge to core proxy with retries and disconnection logic.
Closes #77 
- `WS   /api/engine/v2/edges?token=${token}`: proxies a `edge` node to a `core`
- `GET /api/engine/v2/edges/:edge_id/token`: returns `{"token": "#{edge_id}_s0m3s3cr3t"}`
- Standard CRUD interface to [PlaceOS::Model::Edge](https://github.com/PlaceOS/models/blob/master/src/placeos-models/edge.cr)
- Safe request body IO accessor. Returns 400 if expected body not present.
- Singleton `core` discovery attached to abstract application controller
> feat: edge to core proxy

- src/placeos-rest-api/controllers/oauth_applications.cr
Restrict OAuth applications endpoint to admin users.
Fixes #84
> fix(controller:oauth_applications): restrict to admin

- .github/workflows/build-dev-image.yml
Filter invalid chars in branch name when generating image tag.
> fix: build action

- shard.lock
- shard.yml
- spec/root_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/utilities/responders.cr
- Add `/users/groups?emails=<emails>` for querying users' groups by email
- Missing parameters yield HTTP status `400` instead of `422`
- Refactor `save_and_respond` to accept a block to mutate a successfully saved entity
> feat: user group query

- .ameba.yml
- spec/helper.cr
- spec/modules_spec.cr
- spec/systems_spec.cr
- spec/triggers_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/cluster.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/session.cr
Fixes a bunch of lints introduced by the latest ameba version.
Includes a `.ameba.yml` that ignores the short block lint in specs.
> style: fix a suite of ameba lints

- shard.yml
- src/placeos-rest-api/controllers/cluster.cr
Don't throw on the missing driver key in cluster status route
> fix(controller:cluster): empty array on key miss

- Dockerfile.test
- shard.lock
- shard.yml
- src/placeos-rest-api/controllers/cluster.cr
Use `id` instead of `core_id` in responses from `../cluster`
> refactor(controller:cluster): use `id` instead of `core_id`

- shard.lock
- shard.yml
- src/constants.cr
- src/placeos-rest-api.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/utilities/responders.cr
- Moves constants to a separate file.
- Consolidates the error responses to the format `{"message": "<text>"}`, as well as merging additional arguments to the response object.
The responder logic is independent of an error. Perhaps it could do with a better name than `render_error`?
> refactor: consolidate error responses

- shard.yml
- src/placeos-rest-api/controllers/drivers.cr
Returns compilation output if present and the driver binary was not found.
> feat(controller:drivers): return compilation output if binary not found

- shard.lock
- shard.override.yml
- shard.yml
- spec/helper.cr
- src/config.cr
- src/logging.cr
- src/placeos-rest-api.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/utilities/current-user.cr
Adds a [raven](github.com/Sija/raven.cr) log backend and a controller level exception handler
> feat: raven (sentry integration)

- spec/repositories_spec.cr
- src/placeos-rest-api/controllers/repositories.cr
Returns a HTTP 400 for requests not applicable to the repository type.
Previously this would result in a HTTP 500 following some [undefined behaviour](https://github.com/PlaceOS/PlaceOS/issues/77#issuecomment-843766980).
> Provide client errors for invalid repository requests

- .github/workflows/ci.yml
- shard.lock
- shard.yml
- spec/session_spec.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/session.cr
Crystal arrays don't shrink... so we need to dup long-lived arrays to resize the internal buffers.
This PR does that and...
- adds some synchronization
- refactors how log contexts are set for websocket sessions
> fix: ensure session/session managers caches are shrunk

- spec/users_spec.cr
- src/placeos-rest-api/controllers/users.cr
Adds support for accepting `login_name` and `staff_id` as secondary id types to the `/api/engine/v2/user/:id` endpoints.
Resolves #157.
> User lookup via secondary indices

- spec/root_spec.cr
- src/placeos-rest-api/controllers/root.cr
Adds missing mock endpoints for upstream version queries and expands logging in case of failure.
> Fix failing version spec

- spec/modules_spec.cr
Marks connected query test case as pending until root cause is resolved via PlaceOS/rubber-soul#20.
> 'Fix' intermittent spec failures

- scripts/crystal-spec.sh
Adds a missing script used in `test`
> test: re-add crystal-spec.sh

- spec/systems_spec.cr
- spec/users_spec.cr
- spec/zones_spec.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/zones.cr
Adds the following endpoints:
- `GET /users/:id/metadata`
- `GET /zones/:id/metadata`
- `GET /systems/:id/metadata`
ID resolution uses the local behaviour provided by the parent controller. This enabled metadata queries directly using new user lookup introduced via #157. `name` query param supported across all endpoints for parity with the base `/metadata` controller.
Closes #158.
> Metadata endpoints on entites

- spec/helper.cr
- spec/root_spec.cr
* **spec**:
* Allow specification of `sys_admin` and `support` on the `authentication` helper
> test: specify admin level on auth header

- shard.lock
- spec/helper.cr
- spec/root_spec.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/root.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/utilities/current-user.cr
Provides a minimal change set need to bump `placeos-models` for compatibility with updated email digests.
Supercedes #179 while #169 is in progress.
> chore: placeos-models ~>5.9

- src/placeos-rest-api/session.cr
casting here raises a runtime error, we'll default to an empty array if not provided
> fix(session): args is optional

- shard.yml
- src/placeos-rest-api/session.cr
- Uses a channel to write to the WebSocket
- Avoids error-prone manipulation of JSON through the use of `String::RawConverter`
> refactor: session writes

- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/root.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/webhook.cr
- src/placeos-rest-api/controllers/zones.cr
Unifies boolean param handling across the API.
Old behaviours are preserved (including empty params)
> refactor(api): unify boolean param handling

- spec/controllers/settings_spec.cr
- Introduces option to specify `sys_admin` and `support` of a generated user in args to `authentication`
- Adds specs for support views on `../settings`
Resolves PlaceOS/backoffice/issues/154
> fix: settings support view

- spec/controllers/edges/connection_manager_spec.cr
- spec/helper.cr
- src/placeos-rest-api/controllers/api_keys.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/authentications.cr
- src/placeos-rest-api/controllers/cluster.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/edges/connection_manager.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/oauth_applications.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/zones.cr
There remain a handful of raw accessed to `params`, however these
require more complex validation that is provided via the accessors in
their current form.
The use of the `Params` object is good.
Ultimately we should use the params object for everything, and to achive
it, we can use modules of param definitions (inlcluding validation).
This would centralise the validations, and ensure minimal duplication of
params across the API surface.
> refactor: param getters

- .github/workflows/ci.yml
- spec/controllers/root_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/root.cr
Use a flag enum to represent the access control flags provided by the [mosquito go auth client](https://github.com/iegomez/mosquitto-go-auth/blob/master/backends/constants/constants.go)
> refactor: mqtt permissions check

- shard.lock
- spec/controllers/mqtt_spec.cr
- spec/controllers/root_spec.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/mqtt.cr
- src/placeos-rest-api/controllers/root.cr
- src/placeos-rest-api/utilities/scopes.cr
see https://github.com/iegomez/mosquitto-go-auth#remote-mode for the very poor details on how this should be implemented.
@w-le the URLs are:
```yaml
jwt_getuser_uri: /api/engine/v2/mqtt/user
jwt_aclcheck_uri: /api/engine/v2/mqtt/access
```
> feat: add helper methods for authenticating MQTT websocket access

- shard.lock
- src/placeos-rest-api/controllers/users.cr
I should probably update the `auth` service to uncheck this flag if someone logs in with it set
NTT have requested this as they don't want the user models going away for resolving data elsewhere in the system, but they don't want the deleted users showing up in searches.
We're also building a driver to periodically sync the user models with Graph API in case users have been disabled at that level.
> feat(users controller): add support for user model soft delete

- src/placeos-rest-api/controllers/systems.cr
Redundant code as the code is in the standard library
> chore: remove `Enumerable#tally_by` implementation

- shard.lock
- spec/controllers/drivers_spec.cr
- spec/controllers/settings_spec.cr
- spec/websocket/session_spec.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/utilities/changefeeds.cr
- Refactor and extract changefeeds on a single document into `Utils::Changefeeds.await_model_change(model : T, timeout, & : T -> Bool) : T? forall T`
- Tidy up some specs and resolve ameba issues
`Channel`s used in single document changefeeds would be closed on timeout, causing the final event to be sent on a closed channel, producing a verbose and innocuous error.
> fix: swallow channel errors in single document changefeeds

- Dockerfile
- spec/controllers/asset_spec.cr
- spec/controllers/modules_spec.cr
- spec/controllers/root_spec.cr
- spec/controllers/settings_spec.cr
- spec/controllers/system-triggers_spec.cr
- spec/controllers/systems_spec.cr
- spec/controllers/triggers_spec.cr
- src/constants.cr
- src/placeos-rest-api/controllers/root.cr
Adds `/platform` to the `Root` controller
```json
// GET /api/engine/v2/platform
{
"version": "<platform-version",
"changelog": "<markdown changelog>"
}
```
This does introduce a build time step where if `PLACE_VERSION` is defined (i.e. not `DEV`), an HTTP request to github is made.
This does not affect development builds but may slow down release builds.
Related https://github.com/PlaceOS/backoffice/issues/210
> feat(controllers:root): add `/platform` to render platform metadata

- src/placeos-rest-api/controllers/api_keys.cr
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/authentications.cr
- src/placeos-rest-api/controllers/brokers.cr
- src/placeos-rest-api/controllers/domains.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/oauth_applications.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/schema.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/zones.cr
- src/placeos-rest-api/utilities/put_redirect.cr
Creates a macro, `put_redirect`, that handles the creation of a redirect of `PUT` to the `PATCH` route.
**Benefits**
DRY code
**Possible drawbacks**
The macro require updating when adding OpenAPI helpers, however this will be done in a single place, so I think it's an overall benefit
> refactor(api): `put_redirect` to prevent manual  update redirect

- src/placeos-rest-api/controllers/api_keys.cr
- src/placeos-rest-api/controllers/asset_instances.cr
- src/placeos-rest-api/controllers/assets.cr
- src/placeos-rest-api/controllers/authentications.cr
- src/placeos-rest-api/controllers/brokers.cr
- src/placeos-rest-api/controllers/domains.cr
- src/placeos-rest-api/controllers/drivers.cr
- src/placeos-rest-api/controllers/edges.cr
- src/placeos-rest-api/controllers/metadata.cr
- src/placeos-rest-api/controllers/modules.cr
- src/placeos-rest-api/controllers/oauth_applications.cr
- src/placeos-rest-api/controllers/repositories.cr
- src/placeos-rest-api/controllers/schema.cr
- src/placeos-rest-api/controllers/settings.cr
- src/placeos-rest-api/controllers/system-triggers.cr
- src/placeos-rest-api/controllers/systems.cr
- src/placeos-rest-api/controllers/triggers.cr
- src/placeos-rest-api/controllers/users.cr
- src/placeos-rest-api/controllers/zones.cr
Small refactor that removes the unnecessary separation of the `current_<model>` and `find_<model>` methods that are very common across the surface of the API. 
**Benefits**
Less code.
> refactor(controllers): remove `find_<model>` from `current_<model>`

- src/placeos-rest-api/controllers/repositories.cr
Adds an endpoint in the repositories controller that returns releases for a given repo
**Benefits**
Now backoffice can access needed release information
**Applicable issues**
https://github.com/PlaceOS/backoffice/issues/255
> feat(repositories): add releases endpoint

- shard.lock
- spec/controllers/edges_spec.cr
- src/placeos-rest-api/controllers/edges.cr
Ensure that the api token is included in the response when creating a new edge while also ensuring it does not persist.
**Benefits**
Backoffice (and any other UI) can now display the api token to the user when creating a new edge.
> fix(controller/edges): include `x_api_token` in Edge creation response

- shard.lock
- src/placeos-rest-api/controllers/application.cr
- src/placeos-rest-api/controllers/metadata.cr
Adds pagination via `offset` and `limit` parameters to `GET ../metadata`
**Benefits**
Pagination of potentially large query results.
**Possible drawbacks**
Users of previous versions may expect all results to be returned.
However, the `Link` header will be set if there are further results in a query
**Applicable issues**
- Resolves #263
> feat(controller/metadata): add pagination for `query` route

- src/placeos-rest-api/controllers/repositories.cr
as the new methods are much faster than the previous when there is no change required
> fix(repositories): inconsistent pull responses

- docker-compose.yml
- shard.lock
- shard.yml
- spec/controllers/edges_spec.cr
- src/placeos-rest-api/controllers/edges.cr
Update the edge controller to generate scope methods using a string as the constant previously used is not available before runtime when the macro runs.
Also add a spec which tests authentication against the real edge control endpoint.
**Benefits**
Edge client can authenticate against the websocket control endpoint.
> test(edge): authentication of edge client with the API

- shard.lock
fixes active model not applying defaults in assignement when updating a model via assignment helpers
> chore(shard.lock): bump dependencies

- shard.lock
- spec/controllers/uploads_spec.cr
- src/placeos-rest-api/controllers/uploads.cr
provide more descriptive errors
> feat(uploads): improve upload validation

- shard.lock
- src/constants.cr
- src/placeos-rest-api/controllers/chat_gpt.cr
- src/placeos-rest-api/controllers/chat_gpt/chat_manager.cr
ensures we have the tokens to continue making requests
> feat(chat_gpt): compress chats once tasks are completed

- src/placeos-rest-api/controllers/systems.cr
Avoid bypassing email initialize method to ensure email is downcased
- fixes https://github.com/PlaceOS/rest-api/issues/401
> fix(systems): prevent bypass of email downcase

- docker-compose.yml
- shard.lock
- spec/controllers/uploads_spec.cr
- src/placeos-rest-api/controllers/uploads.cr
allows comparing values with a 3rd party without downloading assets
> feat(uploads): add cache helpers
